resolver: lts-6.14
# This is really old so that you can `stack install haste-compiler` and it will have the right GHC to actually work.
# The next piece of magic is `stack exec haste-boot`

packages:
- .

extra-deps:
- GLFW-0.5.2.5
- ghc-simple-0.3
- shellmate-0.3.4.2
- shellmate-extras-0.3.4.1
- http-conduit-2.2.4
- http-client-0.5.12
- http-client-tls-0.3.5.3
